### PR TITLE
Added migration to change the users DCE column

### PR DESCRIPTION
**Pull request by kristenmills**

### CODE REVIEW

**Comment by kristenmills** [comment]
https://github.com/sequelize/sequelize/issues/3918
Dumb sequelize. Nevermind.

**Comment by 7imbrook** [comment]
```
 1) Agenda "before each" hook: beforeEachHelper for "should return a 200 response":

     SequelizeDatabaseError: SQLITE_ERROR: foreign key mismatch - "headcounts" referencing "users"

      at [object Object].Query.formatError (node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)

      at afterExecute (node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)

      at Statement.errBack (node_modules/sqlite3/lib/sqlite3.js:16:21)
```
@kristenmills

**Comment by kristenmills** [comment]
See previous comment

**Comment by 7imbrook** [comment]
sooo...

**Comment by kristenmills** [comment]
Sequelize is trash. I can't modify the primary key column in a migration. I'll look into a solution later

**Pull request closed without merging**
