### PR TITLE
Go Links redirects to node api`

### PR DESCRIPTION
**Pull request by 7imbrook**
Oh look more stuff was on devlop...

### CODE REVIEW

**Comment by 7imbrook** [comment]
We want to consolidate the tech stack, there are more moving part then there needs to be.

**Comment by kristenmills** [comment]
By your argument, we should also put Slushbot in the API as well as SSELol.

**Comment by 7imbrook** [comment]
I'm not opposed to this

**Comment by billdybas** [comment]
How does `go` submit and resolve links right now? What specifically does `go` do that requires it to need its own server? What are the tradeoffs of keeping `go` separate from the API?

**Comment by kristenmills** [comment]
@7imbrook I could live with it as well. I think we should either commit to having one repo handle the node backend or separate concerns properly.  None of this wishy-washy bullshit where because go has one simple endpoint, that's enough justification for it to be in node api.

@billdybas Go the app itself is responsible for redirecting to the url. So like if I hit sse.rit.edu/go/google, go is responsible for querying the API and then redirects to https://google.com. Timbrook's proposal basically moves that logic to node-api. So if I hit sse.se.rit.edu/go/google it will redirect to sse.rit.edu/api/v1/links/go/google which will then redirect you to https://google.com.  To my point, I think go should be responsible for doing go things. Timbrook is arguing that consolidating is better.

**Comment by 7imbrook** [comment]
@kristenmills that's not what I'm saying, it would rewrite on the nginx layer to `/go/<query>` to `/api/v1/links/go/<query>` in a single call. vs what happens now where the go node server makes an additional call to the node-api to get the link. This actually makes one less call. Not one more. And where we stand now, go's functionality is split between go and node api. If we truly wanted go to be it's own app. Then we pull go link creation out of node api.

**Comment by billdybas** [comment]
I like that the API handles storing the `go` links. This gives the ability to create and use them in other SSE apps.

I agree with @kristenmills that adding the link resolving to the API would add another responsibility to the API, one which is too narrowly focused, and traditionally, it's the client app's responsibility to interact with the data from the API. 

Hypothetically, what if I wanted to use `go` as a link shortener for my own API and that I could replace the SSE API Client with my own similarly implemented API Client? According to @7imbrook's proposal, that would mean I would also have to make modifications to my own API in order for the URLs to be properly resolved, since `go` would no longer do that for me. For that reason, I agree with @kristenmills that this PR shouldn't be merged.

**Comment by kristenmills** [comment]
> @kristenmills that's not what I'm saying, it would rewrite on the nginx layer to /go/<query> to /api/v1/links/go/<query> in a single call. vs what happens now where the go node server makes an additional call to the node-api to get the link. This actually makes one less call. Not one more.

I wasn't trying to justify the number of calls (I'm aware how it will be implemented) I was just stating the flow.  Which is /go => /api/v1/links/go => link

I like having the API be responsible for storing and fetching data. If you want to make a monolithic solution, make a monolithic solution but either go all in or don't go in at all, .

**Comment by wadeanthony0100** [comment]
> If we truly wanted go to be it's own app. Then we pull go link creation out of node api.
What's the reasoning behind making it its own independant app?

**Comment by kristenmills** [comment]
> Hypothetically, what if I wanted to use go as a link shortener for my own API and that I could replace the SSE API Client with my own similarly implemented API Client? According to @7imbrook's proposal, that would mean I would also have to make modifications to my own API in order for the URLs to be properly resolved, since go would no longer do that for me.

I think most of the SSE's things are heavily tied to the SSE so I wouldn't necessarily use this as an argument against timbrook's solution. If we really wanted go to be a stand alone app, we should pull it out entirely.  (Which I don't think we should do)

**Comment by wadeanthony0100** [comment]
> If we really wanted go to be a stand alone app, we should pull it out entirely. (Which I don't think we should do)

I agree that it makes the most sense to either 

- make it its own entity entirely, or
- leave it as implemented. 

We don't currently integrate our `go` data with other data, but I can think of possible future applications that could benefit from having it be part of the single data store. It makes a lot of sense in my mind to keep it as is. To @billdybas 's point, there could be other uses for the data store. I do see the value in simplifying it by shoving it all into the API, but the abstraction exists in all the other apps, and it's kinda nice not to have this one exception that requires some Nginx configuration to work

**Comment by kristenmills** [comment]
@wadeanthony0100 
> I do see the value in simplifying it by shoving it all into the API, but the abstraction exists in all the other apps, and it's kinda nice not to have this one exception that requires some Nginx configuration to work

For clarification: We use nginx for all client side the apps right now. So in actuality, go is the exception because the way it is now, it requires a node server as opposed to the rest, where the static files can be served easily through nginx. 

To your other points, I agree. I like have the single data store and abstracting out all other aspects.

**Comment by vuzDylan** [comment]
@7imbrook @kristenmills 
Here is my 2 cents:
I think that if we are going to do this then a new service should be created that either
A. Has direct access to the database or
B. Queries the Node API
and then redirects users accordingly. I feel that this has no business being part of the node-api because it is that... a node api. I also feel that the current way we are doing it on the front end is not correct. This solution although not as Consolidated as timbrook wants leads to a better separation of actual concerns. Then we just throw nginx in front of all of it and route /go to this service and create a new link for the admin interface on the websight

**Comment by wadeanthony0100** [comment]
I also like this. If we leave the node API for CRUD tasks, then another node instance can query the API and toss redirects to the client. No client side hacks, no weird API responses.

**Comment by 7imbrook** [comment]
@wadeanthony0100 client side redirects are slow and blocked by some browsers/user preference. It is 100% possible to write this as an openresty (nginx fork) lua script that can query and do the redirect for us. This however puts more "logic" into nginx than some would want.

**Comment by vuzDylan** [comment]
I also agree we should not do client side redirects but we also should not put this on the node-api

**Comment by kristenmills** [comment]
I don't think anyone said anything about client side redirects. But I'm fine with Dylan's proposal.

**Comment by 7imbrook** [comment]
@kristenmills @vuzDylan This is what we have now

**Comment by vuzDylan** [comment]
I am aware that we have that now

**Comment by wadeanthony0100** [comment]
I wasn't implying we should use client side redirects, I was under the impression that was what we had now. If there's a refactor to be made, the go interface should be served statically like the other apps for consistency.

**Comment by 7imbrook** [comment]
So the way are apps are served need to fundamentally change because we run a web server in node for each app, that sits behind a nginx proxy, when nginx could serve them more efficiently. This _IS_ and issue because our app count is higher then our available cores, which causes unneed resource contention on the machine. #opsTalk I want to minimize the number of pointless process on the VM.

**Comment by vuzDylan** [comment]
When I am done with the new website it will be dist dir that can be served by ngnix it will not longer be served by a bunch of node servers

**Comment by 7imbrook** [comment]
@vuzDylan for all the apps? How are you planning on doing that?

**Comment by vuzDylan** [comment]
I am still debating what I am going to do about static pages because I havent come up with a great solution to that problem yet.

**Comment by vuzDylan** [comment]
I may just right a webpack plugin to bring them into the front end bundle but I'm not really sure yet

**Comment by 7imbrook** [comment]
@vuzDylan are we keeping separate repos? and will the edge case of `/events/blah/` being a 404, and for the static just keep the jekyll builds. they can all deploy as separate apps, they just need to build a dist.zip to ship (yes over docker)

**Comment by vuzDylan** [comment]
Yes I can handle 404s on the client and as of right now it is one repo because it is one app... but I could be convinced to break it up into different repos that get pulled in at build time but atm that seems like a lot of over engineering so such a simple application

**Comment by vuzDylan** [comment]
The reason I don't want them to be sperate apps is because they all have shared state.

**Comment by 7imbrook** [comment]
We should sitebar that discussion because there are thoughts about bringing events into crazy-train (like you know gtv is). And keeping separate apps separate.

**Comment by vuzDylan** [comment]
The problem with that is that it breaks up the website into all these little pieces that all share the same look, feel, and state. My solution is that we just create a single application for all of our front end application that belong together (events, scoreboard, officers, mentoring(new), QDB, go). Static pages can and probable should continue being served by jekkyl. The go redirects should probably be handled by there own micro service. It should not be added to the node-api because they have nothing to do with each other. The consolidation that you are looking for will come with the rebuild of the current application.

**Comment by 7imbrook** [comment]
@vuzDylan agree, but some apps should remain separate for PR reasons (qdb and maybe scoreboard) This is where a component repo might be useful.

**Comment by vuzDylan** [comment]
Okay so I can make them "separate apps", but I am still going to build them into one dist dir so that I can share state between them. Is that an okay solution?

**Comment by 7imbrook** [comment]
What do you mean by share state?? Also we sitebared this discussion

**Comment by vuzDylan** [comment]
Shared state in and of the fact that the front page shows events which mean we have to pull events, the front page is going to show the mentor which means we pull the mentor. All of the app on our site can be signed into which is also shared state. Also the navigation should remain the same across all apps which can be done by making it a standard component but I still don't feel the need lose state every time someone switch "apps". I don't think the problem is complicated enough for such a solution. Also if it is created as one 'App' be that how ever we do it there will be no page loads when you switch apps which is neat.  (I can async load in those pages). Id like to make it as one app (one repo) but if you think it is necessary I can split it up into differnt apps (repos) and then pull it all in at build time. The last solution that I don't like... but it is still a solution is to make a standard set of components and build 5(idk how many there actually are) different apps and then use webpack to bundle up the common chunks and serve it as 5 different apps.

**Comment by 7imbrook** [comment]
@vuzDylan I head you but this isn't what this issue is about

**Pull request closed without merging**
