### PR TITLE
Better auth

### PR DESCRIPTION
**Pull request by vuzDylan**
Don't know why verifyUser isn't a top level MW but i guess it dons't need to be.

### CODE REVIEW

**Comment by kristenmills** [comment]
Do not merge this yet.  I'll explain in a second.

**Comment by kristenmills** [comment]
You probably should use the regular JWT middleware instead of verify user.  Verify user was created for routes that are have some resources that need to protected by auth but some that don't. (IE getting a quote or membership).

**Comment by vuzDylan** [comment]
were does the regular jwt stick its info then ? i tried getting req.auth and it would come back undeffined

**Comment by vuzDylan** [comment]
or wait is that a function i have to add to the request

**Comment by kristenmills** [comment]
https://github.com/rit-sse/node-api/blob/master/app.js#L18

**Comment by kristenmills** [comment]
Actually it might be a pain to allow a single get request. If it is, don't do it this way.

**Comment by vuzDylan** [comment]
ill check it out and apease the linter on the other one

**Comment by vuzDylan** [comment]
I understand why you don't check the jwt on a get request but is there any real reason that it would be bad to just do it? I mean yes it will slow things down... but is it really a big deal. I mean I guess it is... So that being the case Ill prob leave it the way that it is.

**Comment by kristenmills** [comment]
Well if you check it on ALL get requests, we wouldn't  be able to make unauthenticated get requests.

**Comment by vuzDylan** [comment]
oh I see I didn't notice that it rejects if there is no token. well then what I'm doing is probably the best way of doing it.

**Pull request merged**
